= Common library
:toc: right
:imagesdir: images

This API provides helper functions.

== Usage

Add the following to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include xplibs.common
}
----

Add the `import` statement to your code:

[source,typescript]
----
import commonLib from '/lib/xp/common';
----

You are now ready to use the API.


== Functions

=== sanitize

Transforms a text string so that it can be safely used in cases where the range of accepted characters is restricted.

Some usage examples for sanitizing are: content or node name, principal name, URL or a file system path etc.

The following changes will be applied to the input text:

 * Convert characters to lowercase (according to the rules of the default locale)
 * Replace punctuation symbols and blank spaces with the hyphen character ('-')
 * Remove some unsafe and invisible Unicode characters
 * Strip duplicated hyphen characters
 * Remove diacritic characters
 * Map letters to the English alphabet (ASCII encoding)

[.lead]
Parameters

`sanitize()` takes a single positional argument: `text` (string) — the text to sanitize.

[.lead]
Returns

*string* : The sanitized text

[.lead]
Example

.Sanitize string
[source,typescript]
----
import {sanitize} from '/lib/xp/common';

const sanitizedText = sanitize("Piña CØLADÆ <script>alert('hi!');</script>");
----

.Sample response
[source,typescript]
----
"pina-coladae-script-alerthi-script"
----
