= Overview of the XP runtime architecture
:toc: right
:imagesdir: runtime/media

The Enonic XP runtime powers all applications running on the platform.

== Introduction

To simplify development, upgrades and maintenance, Enonic XP was built like an operating system where developers can rely on the version of the platform when building Enonic apps. 

<<framework#,Enonic's JavaScript framework>> execute on top of the runtime, which means they have access to XP's platform services, such as the <<storage#, NoSQL Storage>>, clustering and CMS features. 

The runtime also provides a <<runtime/engines#, execution pipeline>> for processing requests, and a <<runtime/task-engine#, task engine>> for running scheduled and on-demand tasks.

== Architecture

The XP runtime is built on top of GraalVM, and a series of open source components. Still, XP apps are primarily developed using JavaScript - thanks to the embedded JavaScript engine and framework. However, due to running on the JVM, XP apps may also run other JVM compatible code and libraries.

=== Modular

The runtime uses the OSGi module system to isolate code (bundles) - and controls the ability to communicate between them. <<apps#, XP Applications>> and XP's system bundles essentially work in the same way - with their own life cycle and ability to install, start, stop and uninstall.

image::runtime-architecture.svg[Simplified view of the XP runtime internals, 900]

The architecture also allow you to run multiple applications in a single runtime. Each application may be built, installed, started and stopped independently - and even cooperate on progressing a single request. This can for instance be seen in the <<runtime/engines#, HTTP engines>> and the execution pipeline. This basically means that most XP apps consume very little resources beyond the actual processing, and that a single runtime may potentially contain many applications which are mostly idle when not executing - similar to a serverless architecture, but without the limitations.

=== Multi-threaded
Unlike popular JavaScript runtimes such as NodeJS, the XP runtime is multi-threaded. This allows for utilisation of multi-core CPUs, true parallell execution, and handling of large loads within a single instance. 

This is also important from a development perspective. Since the XP runtime is multi-threaded, developers also benefit from a simplified development model, debugging, and the ability to run threaded operations when needed. XP's <<runtime/task-engine#, task engine>> for instance runs all tasks as separate threads.


=== Optimised

XP apps can benefit from the highly optimised JVM, but also optimisations in XP's JavaScript framework. Also, the highly performance NoSQL storage enable access to large datasets with minimal latency.

== Stateful and stateless

The XP runtime is capable of running in both stateful (using the embedded NoSQL storage) and stateless mode.

== Scalable

XP can easily be scaled by setting up a <<deployment/strategies#, cluster of runtime nodes>>.
It can run in virtually any infrastructure, and also be managed by Kubernetes or similar container orchestration engines for automatic scaling and more.

== Management and metrics API

The runtime provides a <<runtime/management#, management API>>, that amongst others support as installation of apps, dumping and loading data. This is commonly accessed using the Enonic CLI. 

Additionally, the runtime also exposes a <<runtime/statistics#, metrics API>>, providing access to runtime statistics. Like many other parts of XP, the metrics API may easily be extended with XP apps, and provide additional data as needed.