= Request pipleline and the web engines
:toc: right
:imagesdir: engines/media

The runtime serves HTTP requests on `port 8080` (customizable) via four purpose-specific endpoints (aka engines)

== Enpoints

A core feature of the XP runtimes is http request handling. `port 8080` (customizable) provides four purpose-specific endpoints (aka engines):

* <<apis#,API>> `/api` - for APIs, microservices and similar
* <<admin#,Admin>> `/admin` - for administrative tasks and management
* <<webapps#,Webapps>> `/webapp` - for web applications
* <<sites#,Sites>> `/site` - for CMS driven websites

Each engine serves a specific purpose and has its own request processing and execution pipeline. However, they all share a common request pipeline:

[[common_request_pipeline]]
=== Common request pipeline

All web engines share a common request pipeline:

image::common-pipeline.svg[Common HTTP request pipeline, 768px]

Vhost filters:: Request routing based on <<../deployment/vhosts#,virtual hosts>>

Java request filters:: Optional Java request filters

Autologin filter::  The <<../deployment/vhosts#,virtual host contextual ID provider>> will be invoked, unless a user already exists in the context

Engine specific pipeline:: Pipeline of the matching web engine will be executed

Auth handler::  Triggered if the pipeline returns a "401: Unauthorized" error code, the contextual ID Provider will be invoked, optionally handling the request

Error handler:: If the pipeline returns an unhandled error (everything but "200: OK") that was not handled by an ID Provider, the contextual error handler will kick in.

Java response filters:: Optional Java response filters

Standard error handler:: Finally, if the request fails with an error that is still unhandled, XP's standard error handler will kick in


== Underscore endpoint

All engines reserve the use of the underscore character `\_` (by itself) to provide contextual access to the <<api#, Universal API>>.

TODO:
This applies to at any location within the URL path hierarchy.
For instance, the following request `+:8080/webapp/<webapp>/_/*+` or `+:8080/site/<project>/<branch>/some/content/_/*+` are reserved.

Contextual APIs:: Provide access to <<#,Http service controllers>> through the `/_/service/*` request pattern

IDprovider Service:: For direct interaction with the contextual <<engines/idprovider-service#,IDprovider>> based on the `/_/idprovider/*` request patterns

